# Generated by Django 5.1.3 on 2026-05-29 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_card_seller_alter_card_image_cartitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="buyer",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="card",
            name="image",
        ),
    ]
