# Generated by Django 5.1.3 on 2026-05-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0003_remove_profile_bio_alter_card_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
