# Generated by Django 5.1.3 on 2026-05-29 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "marketplace",
            "0004_remove_order_card_card_created_at_card_image_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="card",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="card_title",
        ),
        migrations.AddField(
            model_name="card",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cards/"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="card",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="marketplace.card",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
