# Generated by Django 5.1.3 on 2026-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_remove_card_image_url_remove_card_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="created_at",
        ),
        migrations.AddField(
            model_name="card",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("uncommon", "Uncommon"),
                    ("rare", "Rare"),
                    ("mythic", "Mythic"),
                ],
                default="common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
